package memory

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	resultdoc "github.com/Clyra-AI/relia/internal/result"
	"github.com/Clyra-AI/relia/internal/yamlmini"
)

type RuleSummary struct {
	ID              string
	Kind            string
	Status          string
	Statement       string
	Confidence      string
	ConfidenceLabel string
	EvidenceCount   string
	Contradictions  string
	ReviewLabel     string
	StatementOrigin string
	LifecycleReason string
	Path            string
	Provenance      []RuleProvenance
}

type RenderOptions struct {
	SchemaVersion string
	ReliaVersion  string
}

type RuleProvenance struct {
	PR           int
	Outcome      string
	URL          string
	ExperienceID string
}

var lifecycleStatuses = []string{"active", "candidate", "stale", "contradicted", "retired"}

func LoadRuleSummaries(root string, options ValidationOptions) ([]RuleSummary, *resultdoc.CommandError) {
	patterns := []string{
		filepath.Join(root, "memory", "rules", "*.yaml"),
		filepath.Join(root, "memory", "rules", "*.yml"),
	}
	var paths []string
	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return nil, internalError(options, "could not inspect memory rule artifacts", err)
		}
		paths = append(paths, matches...)
	}
	sort.Strings(paths)
	var summaries []RuleSummary
	for _, path := range paths {
		if commandErr := ValidateRuleArtifact(root, path, options); commandErr != nil {
			return nil, commandErr
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return nil, internalError(options, "could not read memory rule artifact", err)
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			rel = path
		}
		rel = filepath.ToSlash(rel)
		document, parseErr := yamlmini.ParseDocument(string(content))
		if parseErr != nil {
			return nil, artifactContractError(options, parseErr.Error(), rel)
		}
		statement, ok := resolvedRuleStatement(document, string(content))
		if !ok || strings.TrimSpace(statement) == "" {
			return nil, artifactContractError(options, "memory rule statement is required", rel)
		}
		summaries = append(summaries, RuleSummary{
			ID:              document.Scalars["id"].Value,
			Kind:            document.Scalars["kind"].Value,
			Status:          document.Scalars["status"].Value,
			Statement:       statement,
			Confidence:      document.Scalars["confidence"].Value,
			ConfidenceLabel: document.Scalars["metadata.confidence_label"].Value,
			EvidenceCount:   document.Scalars["evidence.count"].Value,
			Contradictions:  document.Scalars["evidence.contradictions"].Value,
			ReviewLabel:     document.Scalars["review.label"].Value,
			StatementOrigin: document.Scalars["review.statement_origin"].Value,
			LifecycleReason: document.Scalars["metadata.lifecycle_reason"].Value,
			Path:            rel,
			Provenance:      RuleProvenanceEntries(document),
		})
	}
	sortRuleSummaries(summaries)
	return summaries, nil
}

func RuleProvenanceEntries(document yamlmini.Document) []RuleProvenance {
	var provenance []RuleProvenance
	for _, entry := range document.ListMaps["provenance"] {
		pr := 0
		if scalar, ok := entry["pr"]; ok {
			pr, _ = strconv.Atoi(scalar.Value)
		}
		provenance = append(provenance, RuleProvenance{
			PR:           pr,
			Outcome:      entry["outcome"].Value,
			URL:          entry["url"].Value,
			ExperienceID: entry["experience_id"].Value,
		})
	}
	sort.Slice(provenance, func(i, j int) bool {
		if provenance[i].PR == provenance[j].PR {
			return provenance[i].ExperienceID < provenance[j].ExperienceID
		}
		return provenance[i].PR < provenance[j].PR
	})
	return provenance
}

func StatusRank(status string) int {
	for index, lifecycleStatus := range lifecycleStatuses {
		if status == lifecycleStatus {
			return index
		}
	}
	return len(lifecycleStatuses)
}

func StatusCounts(rules []RuleSummary) map[string]int {
	counts := map[string]int{}
	for _, status := range lifecycleStatuses {
		counts[status] = 0
	}
	for _, rule := range rules {
		counts[rule.Status]++
	}
	return counts
}

func RenderMarkdown(rules []RuleSummary, options ...RenderOptions) string {
	rules = sortedRuleSummaries(rules)
	renderOptions := defaultRenderOptions(options)
	var builder strings.Builder
	builder.WriteString("<!-- relia:memory-page generated; schema_version=" + renderOptions.SchemaVersion + "; relia_version=" + renderOptions.ReliaVersion + "; source=memory/rules -->\n")
	builder.WriteString("# Relia Memory\n\n")
	builder.WriteString("Generated by `relia memory` from reviewed local memory rule artifacts.\n\n")
	builder.WriteString("- schema version: `" + renderOptions.SchemaVersion + "`\n")
	builder.WriteString("- relia version: `" + renderOptions.ReliaVersion + "`\n")
	builder.WriteString("- source of truth: `memory/rules/*.yaml`\n\n")
	if len(rules) == 0 {
		builder.WriteString("No memory rules found.\n\n")
	}
	builder.WriteString("## Lifecycle Summary\n\n")
	renderStatusSummary(&builder, rules)
	builder.WriteString("## Strong Memory\n\n")
	builder.WriteString("Active accepted rules are eligible for serving and assessment.\n\n")
	activeRules := filterRulesByActiveStatus(rules, true)
	if len(activeRules) == 0 {
		builder.WriteString("No active accepted rules.\n\n")
	} else {
		renderRulesByStatus(&builder, activeRules)
	}
	builder.WriteString("## Weak Memory\n\n")
	builder.WriteString("Candidate, stale, contradicted, and retired rules are visible for review but are not served as active memory.\n\n")
	weakRules := filterRulesByActiveStatus(rules, false)
	if len(weakRules) == 0 {
		builder.WriteString("No weak memory rules.\n")
		return builder.String()
	}
	renderRulesByStatus(&builder, weakRules)
	return builder.String()
}

func defaultRenderOptions(options []RenderOptions) RenderOptions {
	renderOptions := RenderOptions{SchemaVersion: "1.0", ReliaVersion: "0.0.0-dev"}
	if len(options) == 0 {
		return renderOptions
	}
	if options[0].SchemaVersion != "" {
		renderOptions.SchemaVersion = options[0].SchemaVersion
	}
	if options[0].ReliaVersion != "" {
		renderOptions.ReliaVersion = options[0].ReliaVersion
	}
	return renderOptions
}

func renderStatusSummary(builder *strings.Builder, rules []RuleSummary) {
	counts := StatusCounts(rules)
	builder.WriteString("| lifecycle | count | serving posture |\n")
	builder.WriteString("| --- | ---: | --- |\n")
	for _, status := range lifecycleStatuses {
		builder.WriteString("| " + status + " | " + strconv.Itoa(counts[status]) + " | " + servingPosture(status) + " |\n")
	}
	builder.WriteString("\n")
}

func sortedRuleSummaries(rules []RuleSummary) []RuleSummary {
	sorted := append([]RuleSummary(nil), rules...)
	sortRuleSummaries(sorted)
	return sorted
}

func sortRuleSummaries(rules []RuleSummary) {
	sort.Slice(rules, func(i, j int) bool {
		left := StatusRank(rules[i].Status)
		right := StatusRank(rules[j].Status)
		if left == right {
			return rules[i].ID < rules[j].ID
		}
		return left < right
	})
}

func filterRulesByActiveStatus(rules []RuleSummary, active bool) []RuleSummary {
	filtered := make([]RuleSummary, 0, len(rules))
	for _, rule := range rules {
		if (rule.Status == "active") == active {
			filtered = append(filtered, rule)
		}
	}
	return filtered
}

func renderRulesByStatus(builder *strings.Builder, rules []RuleSummary) {
	currentStatus := ""
	for _, rule := range rules {
		if rule.Status != currentStatus {
			currentStatus = rule.Status
			builder.WriteString("### " + titleCaseStatus(currentStatus) + "\n\n")
		}
		builder.WriteString("#### " + rule.ID + "\n\n")
		builder.WriteString("- kind: `" + rule.Kind + "`\n")
		builder.WriteString("- status: `" + rule.Status + "`\n")
		builder.WriteString("- lifecycle: `" + rule.Status + "` (" + servingPosture(rule.Status) + ")\n")
		if strings.TrimSpace(rule.LifecycleReason) != "" {
			builder.WriteString("- lifecycle reason: " + rule.LifecycleReason + "\n")
		}
		confidence := rule.Confidence
		if rule.ConfidenceLabel != "" {
			confidence += " (" + rule.ConfidenceLabel + ")"
		}
		builder.WriteString("- confidence: " + confidence + "\n")
		builder.WriteString("- review: `" + rule.ReviewLabel + "` from `" + rule.StatementOrigin + "`\n")
		builder.WriteString("- evidence: " + rule.EvidenceCount + " experiences, " + rule.Contradictions + " contradictions\n")
		builder.WriteString("- statement: " + rule.Statement + "\n")
		if len(rule.Provenance) > 0 {
			builder.WriteString("- receipts:\n")
			for _, receipt := range provenanceReceiptLines(rule.Provenance) {
				builder.WriteString("  - " + receipt + "\n")
			}
		}
		builder.WriteString("- artifact: `" + rule.Path + "`\n\n")
	}
}

func servingPosture(status string) string {
	if status == "active" {
		return "served as strong memory"
	}
	return "visible only; not served"
}

func titleCaseStatus(status string) string {
	if status == "" {
		return "Unknown"
	}
	return strings.ToUpper(status[:1]) + strings.ReplaceAll(status[1:], "_", " ")
}

func provenanceReceiptLines(provenance []RuleProvenance) []string {
	seen := map[string]bool{}
	var receipts []string
	for _, ref := range provenance {
		if ref.URL == "" || ref.PR <= 0 {
			continue
		}
		receipt := fmt.Sprintf("[PR #%d](%s)", ref.PR, ref.URL)
		if ref.Outcome != "" {
			receipt += " - outcome `" + ref.Outcome + "`"
		}
		if ref.ExperienceID != "" {
			receipt += ", experience `" + ref.ExperienceID + "`"
		}
		if seen[receipt] {
			continue
		}
		seen[receipt] = true
		receipts = append(receipts, receipt)
	}
	return receipts
}
