package memory

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	resultdoc "github.com/Clyra-AI/relia/internal/result"
	"github.com/Clyra-AI/relia/internal/yamlmini"
)

type RuleSummary struct {
	ID              string
	Kind            string
	Status          string
	Statement       string
	Confidence      string
	ConfidenceLabel string
	EvidenceCount   string
	Contradictions  string
	ReviewLabel     string
	StatementOrigin string
	Path            string
	Provenance      []RuleProvenance
}

type RuleProvenance struct {
	PR           int
	Outcome      string
	URL          string
	ExperienceID string
}

func LoadRuleSummaries(root string, options ValidationOptions) ([]RuleSummary, *resultdoc.CommandError) {
	patterns := []string{
		filepath.Join(root, "memory", "rules", "*.yaml"),
		filepath.Join(root, "memory", "rules", "*.yml"),
	}
	var paths []string
	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return nil, internalError(options, "could not inspect memory rule artifacts", err)
		}
		paths = append(paths, matches...)
	}
	sort.Strings(paths)
	var summaries []RuleSummary
	for _, path := range paths {
		if commandErr := ValidateRuleArtifact(root, path, options); commandErr != nil {
			return nil, commandErr
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return nil, internalError(options, "could not read memory rule artifact", err)
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			rel = path
		}
		rel = filepath.ToSlash(rel)
		document, parseErr := yamlmini.ParseDocument(string(content))
		if parseErr != nil {
			return nil, artifactContractError(options, parseErr.Error(), rel)
		}
		summaries = append(summaries, RuleSummary{
			ID:              document.Scalars["id"].Value,
			Kind:            document.Scalars["kind"].Value,
			Status:          document.Scalars["status"].Value,
			Statement:       document.Scalars["statement"].Value,
			Confidence:      document.Scalars["confidence"].Value,
			ConfidenceLabel: document.Scalars["metadata.confidence_label"].Value,
			EvidenceCount:   document.Scalars["evidence.count"].Value,
			Contradictions:  document.Scalars["evidence.contradictions"].Value,
			ReviewLabel:     document.Scalars["review.label"].Value,
			StatementOrigin: document.Scalars["review.statement_origin"].Value,
			Path:            rel,
			Provenance:      RuleProvenanceEntries(document),
		})
	}
	sort.Slice(summaries, func(i, j int) bool {
		left := StatusRank(summaries[i].Status)
		right := StatusRank(summaries[j].Status)
		if left == right {
			return summaries[i].ID < summaries[j].ID
		}
		return left < right
	})
	return summaries, nil
}

func RuleProvenanceEntries(document yamlmini.Document) []RuleProvenance {
	var provenance []RuleProvenance
	for _, entry := range document.ListMaps["provenance"] {
		pr := 0
		if scalar, ok := entry["pr"]; ok {
			pr, _ = strconv.Atoi(scalar.Value)
		}
		provenance = append(provenance, RuleProvenance{
			PR:           pr,
			Outcome:      entry["outcome"].Value,
			URL:          entry["url"].Value,
			ExperienceID: entry["experience_id"].Value,
		})
	}
	sort.Slice(provenance, func(i, j int) bool {
		if provenance[i].PR == provenance[j].PR {
			return provenance[i].ExperienceID < provenance[j].ExperienceID
		}
		return provenance[i].PR < provenance[j].PR
	})
	return provenance
}

func StatusRank(status string) int {
	switch status {
	case "active":
		return 0
	case "candidate":
		return 1
	case "contradicted":
		return 2
	case "stale":
		return 3
	case "retired":
		return 4
	default:
		return 5
	}
}

func StatusCounts(rules []RuleSummary) map[string]int {
	counts := map[string]int{}
	for _, rule := range rules {
		counts[rule.Status]++
	}
	return counts
}

func RenderMarkdown(rules []RuleSummary) string {
	var builder strings.Builder
	builder.WriteString("# Relia Memory\n\n")
	builder.WriteString("Generated by `relia memory` from reviewed local memory rule artifacts.\n\n")
	if len(rules) == 0 {
		builder.WriteString("No memory rules found.\n")
		return builder.String()
	}
	builder.WriteString("## Strong Memory\n\n")
	builder.WriteString("Active accepted rules are eligible for serving and assessment.\n\n")
	activeRules := filterRulesByActiveStatus(rules, true)
	if len(activeRules) == 0 {
		builder.WriteString("No active accepted rules.\n\n")
	} else {
		renderRulesByStatus(&builder, activeRules)
	}
	builder.WriteString("## Weak Memory\n\n")
	builder.WriteString("Candidate, stale, contradicted, and retired rules are visible for review but are not served as active memory.\n\n")
	weakRules := filterRulesByActiveStatus(rules, false)
	if len(weakRules) == 0 {
		builder.WriteString("No weak memory rules.\n")
		return builder.String()
	}
	renderRulesByStatus(&builder, weakRules)
	return builder.String()
}

func filterRulesByActiveStatus(rules []RuleSummary, active bool) []RuleSummary {
	filtered := make([]RuleSummary, 0, len(rules))
	for _, rule := range rules {
		if (rule.Status == "active") == active {
			filtered = append(filtered, rule)
		}
	}
	return filtered
}

func renderRulesByStatus(builder *strings.Builder, rules []RuleSummary) {
	currentStatus := ""
	for _, rule := range rules {
		if rule.Status != currentStatus {
			currentStatus = rule.Status
			builder.WriteString("### " + titleCaseStatus(currentStatus) + "\n\n")
		}
		builder.WriteString("#### " + rule.ID + "\n\n")
		builder.WriteString("- kind: `" + rule.Kind + "`\n")
		builder.WriteString("- status: `" + rule.Status + "`\n")
		confidence := rule.Confidence
		if rule.ConfidenceLabel != "" {
			confidence += " (" + rule.ConfidenceLabel + ")"
		}
		builder.WriteString("- confidence: " + confidence + "\n")
		builder.WriteString("- review: `" + rule.ReviewLabel + "` from `" + rule.StatementOrigin + "`\n")
		builder.WriteString("- evidence: " + rule.EvidenceCount + " experiences, " + rule.Contradictions + " contradictions\n")
		builder.WriteString("- statement: " + rule.Statement + "\n")
		if len(rule.Provenance) > 0 {
			builder.WriteString("- provenance: " + strings.Join(provenanceLinks(rule.Provenance), ", ") + "\n")
		}
		builder.WriteString("- artifact: `" + rule.Path + "`\n\n")
	}
}

func titleCaseStatus(status string) string {
	if status == "" {
		return "Unknown"
	}
	return strings.ToUpper(status[:1]) + strings.ReplaceAll(status[1:], "_", " ")
}

func provenanceLinks(provenance []RuleProvenance) []string {
	seen := map[string]bool{}
	var links []string
	for _, ref := range provenance {
		if ref.URL == "" || ref.PR <= 0 {
			continue
		}
		link := fmt.Sprintf("[PR #%d](%s)", ref.PR, ref.URL)
		if seen[link] {
			continue
		}
		seen[link] = true
		links = append(links, link)
	}
	return links
}
